-- Baseline migration file generated by drizzle-kit pull.
-- This repository uses the live database as the baseline truth.
-- DO NOT attempt to (re)create tables from introspection here.
-- Kept as a placeholder so the migration chain remains consistent.

-- no-op
SELECT 1;
